# See build status from:
# https://travis-ci.org/kerolasa/outlier
dist: trusty
sudo: false
language: c
compiler:
  - gcc
  - clang
python:
  - 3.6
addons:
  apt:
    packages:
      - "python3-pip"
install:
  - mkdir ninjadir
  - export PATH="`pwd`/ninjadir:${PATH}"
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip -d ninjadir
  - pip3 install meson
script:
  - meson build
  - ninja -C build test
