# See build status from:
# https://travis-ci.org/kerolasa/outlier
dist: trusty
sudo: false
language: python
python: 3.6
addons:
  apt:
    packages:
      - "python3-pip"
install:
  - export NINJA_LATEST="https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip"
  - wget "$NINJA_LATEST"
  - unzip -q ninja-linux.zip -d build
  - export PATH="$PWD/build:$PATH"
  - pip3 install meson
script:
  - meson build
  - ninja -C build test
