.TH OUTLIER "1" "2014-06-14" "outlier" "User Commands"
.SH NAME
outlier \- find outlier limits from numeric input
.SH SYNOPSIS
.B outlier
[options]
.I [file]
.SH DESCRIPTION
This command reads from input files, or stdin when file argument is
omitted, numeric input and does statistics analysis to the values.
Output put has is printed to each input file separately, and it contains
.I lof
(low fench),
.I q1
(first quartile),
.IR mean ,
.I q1
(third quartile),
.I hif
(high fench),
.I range
how much values differ, and
.I samples
that tells how many data points the calculation got as an input.  The
output is same as what is basis of a traditional boxplot.
.SH OPTIONS
.TP
\fB\-m\fR, \fB\-\-min\fR \fIvalue\fR
Minimum allowed value.  When
.I lof
is calculated to be smaller the minimum value is printed instead.
.TP
\fB\-x\fR, \fB\-\-max\fR \fIvalue\fR
Maximum allowed value.  When
.I hif
is calculated to be greater the maximum value is printed instead.
.TP
\fB\-r\fR, \fB\-\-rrdxml\fR
Read rrd archive database row values from
.B rrdtool dump
xml output.
.TP
\fB\-w\fR, \fB\-\-whiskers\fR \fImultiplier\fR
Multiply interquartile range by a floating point number, to set
.I lof
and
.I hif
to be closer
.RI ( multiplier
< 1.0) or further
.RI "(1.0 < " multplier ).
The default multiplier is
.BR 1.5 .
If the dump has in definition for min and/or max data set values they are
used as a minimun and maximum printout values for
.I lof
and
.I hif
when the calculated value is out of range.
.TP
\fB\-V\fR, \fB\-\-version\fR
Display version information and exit.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help and exit.
.SH EXAMPLE
Dump rrd a file, filter output to contain only measurement values, and
analyze.
.PP
.nf
rrdtool dump file.rrd | outlier --rrdxml
cat lots_of_numbers | outlier
outlier input_file_1 input_file_2
.fi
.SH NOTES
This command was originally wrote to assist finding reasonable alarming
thresholds from rrd files.  The
.I lof
and
.I hif
can be considered as a reasonable guess when a measurement exceeds limit
of begin normal, and an alarm should be sent.
.SH "SEE ALSO"
.BR rrdtool (1) ,
.UR http://en.wikipedia.org/wiki/Box_plot
.UE
.SH AVAILABILITY
The outlier command can be found from
.UR https://github.com/kerolasa/outlier/
github
.UE .
