#!/bin/bash

IAM="${0##*/}"

if [ ! -d tests/outputs ]; then
	mkdir tests/outputs
fi

>| tests/outputs/$IAM

echo "zero" >> tests/outputs/$IAM
outlier -w 0 tests/inputs/simple.dat >> tests/outputs/$IAM

echo "one" >> tests/outputs/$IAM
outlier --whiskers 1 tests/inputs/simple.dat >> tests/outputs/$IAM

echo "1024" >> tests/outputs/$IAM
outlier --whiskers 1024 tests/inputs/simple.dat >> tests/outputs/$IAM

echo "1048576" >> tests/outputs/$IAM
outlier --whiskers 1048576 tests/inputs/simple.dat >> tests/outputs/$IAM

diff -u $top_srcdir/tests/expected/$IAM tests/outputs/$IAM
exit $?
